[package]
name = "updater"
version = "0.1.0"
edition = "2024"

[dependencies]
colog = "1.4.0"
color-eyre = "0.6.5"
dump-roblox-api = "1.0.2"
log = "0.4.29"
reqwest = "0.12.24"
tokio = {version = "1.48.0", features = ["full"]}
